In [2]:
import numpy as np

In [3]:
l=[1,2,3,4,5,6]

In [4]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [5]:
l1=[3,4,2,5,'Sudh',32.4,True]

In [11]:
a1=np.array(l1)

In [12]:
a2=np.array([[1,2,3,4],[64,6,46,7]])

In [15]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [16]:
a1.ndim

1

In [17]:
a3.ndim

3

In [18]:
a1.size

7

In [19]:
a3.size

9

In [20]:
a1.shape

(7,)

In [21]:
a3.shape

(1, 3, 3)

In [22]:
a2.shape

(2, 4)

In [23]:
a2

array([[ 1,  2,  3,  4],
       [64,  6, 46,  7]])

In [24]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [34]:
np.random.randint(2,30, (3,4))

array([[20,  5, 24,  9],
       [28, 20, 27, 17],
       [21,  2,  5, 11]])

In [35]:
np.random.randint(2,30, (2,3,4))

array([[[18, 27, 29, 16],
        [14, 18,  7, 29],
        [ 7, 13, 17,  8]],

       [[15,  9, 28, 18],
        [13, 21,  9,  3],
        [27, 26, 19, 17]]])

In [36]:
np.random.rand(2,3)

array([[0.65767324, 0.84237822, 0.44579072],
       [0.58213123, 0.66009387, 0.25832483]])

In [38]:
a4=np.random.randn(4,4)

In [39]:
a4

array([[-0.64492793,  0.34930415, -0.66112894,  0.67672158],
       [-0.94069651,  1.21912343,  1.28832328, -1.64939086],
       [-0.97086925,  0.17944697,  0.0609291 , -0.04854548],
       [-0.48541342,  1.11488454,  0.40290883, -1.07415   ]])

In [40]:
a4.reshape(2,2,4)

array([[[-0.64492793,  0.34930415, -0.66112894,  0.67672158],
        [-0.94069651,  1.21912343,  1.28832328, -1.64939086]],

       [[-0.97086925,  0.17944697,  0.0609291 , -0.04854548],
        [-0.48541342,  1.11488454,  0.40290883, -1.07415   ]]])

In [41]:
a4.reshape(8,2)

array([[-0.64492793,  0.34930415],
       [-0.66112894,  0.67672158],
       [-0.94069651,  1.21912343],
       [ 1.28832328, -1.64939086],
       [-0.97086925,  0.17944697],
       [ 0.0609291 , -0.04854548],
       [-0.48541342,  1.11488454],
       [ 0.40290883, -1.07415   ]])

In [42]:
a4.reshape(2,8)

array([[-0.64492793,  0.34930415, -0.66112894,  0.67672158, -0.94069651,
         1.21912343,  1.28832328, -1.64939086],
       [-0.97086925,  0.17944697,  0.0609291 , -0.04854548, -0.48541342,
         1.11488454,  0.40290883, -1.07415   ]])

In [43]:
a4.reshape(2,-1)

array([[-0.64492793,  0.34930415, -0.66112894,  0.67672158, -0.94069651,
         1.21912343,  1.28832328, -1.64939086],
       [-0.97086925,  0.17944697,  0.0609291 , -0.04854548, -0.48541342,
         1.11488454,  0.40290883, -1.07415   ]])

In [44]:
a4.reshape(2,-1543535)

array([[-0.64492793,  0.34930415, -0.66112894,  0.67672158, -0.94069651,
         1.21912343,  1.28832328, -1.64939086],
       [-0.97086925,  0.17944697,  0.0609291 , -0.04854548, -0.48541342,
         1.11488454,  0.40290883, -1.07415   ]])

In [45]:
a4.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[-0.64492793,  0.34930415, -0.66112894,
                 0.67672158],
               [-0.94069651,  1.21912343,  1.28832328,
                -1.64939086]],

              [[-0.97086925,  0.17944697,  0.0609291 ,
                -0.04854548],
               [-0.48541342,  1.11488454,  0.40290883,
                -1.07415   ]]]]]]]]]])

In [46]:
a1

array(['3', '4', '2', '5', 'Sudh', '32.4', 'True'], dtype='<U32')

In [47]:
a1[0]

'3'

In [48]:
a1[2:6]

array(['2', '5', 'Sudh', '32.4'], dtype='<U32')

In [49]:
a2

array([[ 1,  2,  3,  4],
       [64,  6, 46,  7]])

In [50]:
a2[0]

array([1, 2, 3, 4])

In [52]:
a2[:,1:]

array([[ 2,  3,  4],
       [ 6, 46,  7]])

In [53]:
a2[:,[1,2]]

array([[ 2,  3],
       [ 6, 46]])

In [55]:
a5=np.random.randint(2,90,(6,5))

In [56]:
a5

array([[62, 72, 88, 11, 13],
       [27, 47, 67, 88, 40],
       [15, 87, 10, 30,  2],
       [11, 39,  9, 82, 42],
       [49, 71, 46, 24, 18],
       [81, 79, 32, 22, 87]])

In [57]:
a5[a5>50]

array([62, 72, 88, 67, 88, 87, 82, 71, 81, 79, 87])

In [58]:
a5

array([[62, 72, 88, 11, 13],
       [27, 47, 67, 88, 40],
       [15, 87, 10, 30,  2],
       [11, 39,  9, 82, 42],
       [49, 71, 46, 24, 18],
       [81, 79, 32, 22, 87]])

In [60]:
a5[0,1]=2

In [61]:
a5

array([[62,  2, 88, 11, 13],
       [27, 47, 67, 88, 40],
       [15, 87, 10, 30,  2],
       [11, 39,  9, 82, 42],
       [49, 71, 46, 24, 18],
       [81, 79, 32, 22, 87]])

In [62]:
a6=np.random.randint(0,3,(3,3))

In [63]:
a6

array([[2, 2, 1],
       [2, 0, 0],
       [2, 1, 2]])

In [64]:
a7=np.random.randint(0,3,(3,3))

In [65]:
a7

array([[2, 0, 1],
       [2, 2, 1],
       [2, 1, 0]])

In [66]:
a6*a7

array([[4, 0, 1],
       [4, 0, 0],
       [4, 1, 0]])

In [67]:
a6+a7

array([[4, 2, 2],
       [4, 2, 1],
       [4, 2, 2]])

In [68]:
np.matmul(a6,a7)

array([[10,  5,  4],
       [ 4,  0,  2],
       [10,  4,  3]])

In [70]:
a6@a7

array([[10,  5,  4],
       [ 4,  0,  2],
       [10,  4,  3]])

In [71]:
a6*2

array([[4, 4, 2],
       [4, 0, 0],
       [4, 2, 4]])

In [72]:
a6/0

C:\Users\Himanshu Verma\AppData\Local\Temp\ipykernel_4736\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\Himanshu Verma\AppData\Local\Temp\ipykernel_4736\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [inf, nan, nan],
       [inf, inf, inf]])

In [73]:
a6

array([[2, 2, 1],
       [2, 0, 0],
       [2, 1, 2]])

In [74]:
a6**3

array([[8, 8, 1],
       [8, 0, 0],
       [8, 1, 8]], dtype=int32)

In [77]:
a8=np.zeros((4,4))

In [80]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
a9=np.ones((4,6))

In [81]:
a9

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [82]:
a9+10

array([[11., 11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11., 11.]])

In [83]:
a9+np.array([1,2,3,4,5,6])

array([[2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7.],
       [2., 3., 4., 5., 6., 7.]])

In [88]:
(a9.T + np.array([1,2,3,4])).T

array([[2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5.]])

In [89]:
a5

array([[62,  2, 88, 11, 13],
       [27, 47, 67, 88, 40],
       [15, 87, 10, 30,  2],
       [11, 39,  9, 82, 42],
       [49, 71, 46, 24, 18],
       [81, 79, 32, 22, 87]])

In [91]:
np.sqrt(a5)

array([[7.87400787, 1.41421356, 9.38083152, 3.31662479, 3.60555128],
       [5.19615242, 6.8556546 , 8.18535277, 9.38083152, 6.32455532],
       [3.87298335, 9.32737905, 3.16227766, 5.47722558, 1.41421356],
       [3.31662479, 6.244998  , 3.        , 9.05538514, 6.4807407 ],
       [7.        , 8.42614977, 6.78232998, 4.89897949, 4.24264069],
       [9.        , 8.88819442, 5.65685425, 4.69041576, 9.32737905]])

In [92]:
np.exp(a5)

array([[8.43835667e+26, 7.38905610e+00, 1.65163625e+38, 5.98741417e+04,
        4.42413392e+05],
       [5.32048241e+11, 2.58131289e+20, 1.25236317e+29, 1.65163625e+38,
        2.35385267e+17],
       [3.26901737e+06, 6.07603023e+37, 2.20264658e+04, 1.06864746e+13,
        7.38905610e+00],
       [5.98741417e+04, 8.65934004e+16, 8.10308393e+03, 4.09399696e+35,
        1.73927494e+18],
       [1.90734657e+21, 6.83767123e+30, 9.49611942e+19, 2.64891221e+10,
        6.56599691e+07],
       [1.50609731e+35, 2.03828107e+34, 7.89629602e+13, 3.58491285e+09,
        6.07603023e+37]])

In [93]:
np.log10(a5)

array([[1.79239169, 0.30103   , 1.94448267, 1.04139269, 1.11394335],
       [1.43136376, 1.67209786, 1.8260748 , 1.94448267, 1.60205999],
       [1.17609126, 1.93951925, 1.        , 1.47712125, 0.30103   ],
       [1.04139269, 1.59106461, 0.95424251, 1.91381385, 1.62324929],
       [1.69019608, 1.85125835, 1.66275783, 1.38021124, 1.25527251],
       [1.90848502, 1.89762709, 1.50514998, 1.34242268, 1.93951925]])

In [97]:
np.log2(a5)

array([[5.95419631, 1.        , 6.45943162, 3.45943162, 3.70043972],
       [4.7548875 , 5.55458885, 6.06608919, 6.45943162, 5.32192809],
       [3.9068906 , 6.4429435 , 3.32192809, 4.9068906 , 1.        ],
       [3.45943162, 5.28540222, 3.169925  , 6.357552  , 5.39231742],
       [5.61470984, 6.14974712, 5.52356196, 4.5849625 , 4.169925  ],
       [6.33985   , 6.30378075, 5.        , 4.45943162, 6.4429435 ]])

In [98]:
list(range(0,20,2.4))

TypeError: 'float' object cannot be interpreted as an integer

In [100]:
np.arange(0.5,20.7,2.5)

array([ 0.5,  3. ,  5.5,  8. , 10.5, 13. , 15.5, 18. , 20.5])

In [103]:
np.linspace(2,2.1,num=20,retstep=True)

(array([2.        , 2.00526316, 2.01052632, 2.01578947, 2.02105263,
        2.02631579, 2.03157895, 2.03684211, 2.04210526, 2.04736842,
        2.05263158, 2.05789474, 2.06315789, 2.06842105, 2.07368421,
        2.07894737, 2.08421053, 2.08947368, 2.09473684, 2.1       ]),
 0.005263157894736847)

In [104]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [105]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=f53e9edba6a00b16a3f981b283dddb6f014c55572c741c86cc146a3b3ceaa3bb
  Stored in directory: c:\users\himanshu verma\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks
Note: you may need to restart the kernel to use updated packages.


In [108]:
import cufflinks as cf
import pandas as pd
import seaborn as sns

In [109]:
cf.go_offline()

In [114]:
df=pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])

In [115]:
df

A         B         C
0  -1.584500 -0.292767 -0.958588
1   0.402982 -1.556814  0.755556
2  -0.704426  0.864839 -2.107934
3  -0.454835  2.512958 -1.312027
4  -0.991454 -0.829157  1.284437
..       ...       ...       ...
95  0.241365  0.736359 -0.913844
96 -0.574219 -0.369452  1.538646
97 -1.146386 -0.830971 -0.858099
98  0.338420 -0.727172 -0.816123
99  0.730394 -0.629229 -0.683849

[100 rows x 3 columns]

In [116]:
df.iplot()

In [118]:
df1=pd.DataFrame(np.random.randint(3,100,(100,1)))

In [119]:
df1

0
0   56
1    4
2   43
3   17
4   24
..  ..
95  36
96  29
97  93
98  69
99   7

[100 rows x 1 columns]

In [120]:
df1.iplot()

In [121]:
df

A         B         C
0  -1.584500 -0.292767 -0.958588
1   0.402982 -1.556814  0.755556
2  -0.704426  0.864839 -2.107934
3  -0.454835  2.512958 -1.312027
4  -0.991454 -0.829157  1.284437
..       ...       ...       ...
95  0.241365  0.736359 -0.913844
96 -0.574219 -0.369452  1.538646
97 -1.146386 -0.830971 -0.858099
98  0.338420 -0.727172 -0.816123
99  0.730394 -0.629229 -0.683849

[100 rows x 3 columns]

In [123]:
df.iplot(x='A',y='B',mode='markers')

In [125]:
df2=sns.load_dataset('titanic')

In [126]:
df2

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [129]:
df2.iplot(x='age',y='fare',mode='markers')

In [130]:
df2.iplot(x='age',y='pclass',mode='markers')

In [132]:
df2.iplot(y='fare',x='pclass',mode='markers')

In [134]:
df2.iplot(kind='bar',x='sex',y='survived')

In [ ]:
http://matrixmultiplication.xyz/

https://github.com/sudh9931/numpy/blob/main/numpy.py