In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [14]:
l1=[4,5,6,7,'sudh',34.56,True]

In [15]:
np.array(l1)

array(['4', '5', '6', '7', 'sudh', '34.56', 'True'], dtype='<U32')

In [16]:
np.array([[1,3,4,5],[7,6,3,2]])

array([[1, 3, 4, 5],
       [7, 6, 3, 2]])

In [21]:
a1=np.array([[[[[[[[[[[32,12,34,4],[3,432,5,44],[34,54,32,54]]]]]]]]]]])

In [22]:
a1

array([[[[[[[[[[[ 32,  12,  34,   4],
                [  3, 432,   5,  44],
                [ 34,  54,  32,  54]]]]]]]]]]])

In [23]:
a1.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4)

In [26]:
a1.ndim

11

In [27]:
a1.size

12

In [30]:
np.array([[[1,3,4,5],[7,6,3,2]],[[1,3,4,5],[7,6,3,2]]]).shape

(2, 2, 4)

In [35]:
np.random.randint(2,50,(2,3,4))

array([[[22, 24, 27, 36],
        [ 8, 31, 24, 18],
        [48, 25, 29,  6]],

       [[11, 24,  4, 22],
        [21,  3, 46, 43],
        [30, 19, 16,  4]]])

In [40]:
np.random.rand(2,3,2)

array([[[0.85924684, 0.79694707],
        [0.00674034, 0.60217378],
        [0.02780994, 0.27109538]],

       [[0.56689023, 0.38787011],
        [0.10223233, 0.62259832],
        [0.18010452, 0.22820263]]])

In [42]:
re=np.random.randn(2,3,2)

In [43]:
re

array([[[ 0.66890184,  0.29318779],
        [ 0.44929895,  0.06175574],
        [ 1.17133333, -0.2299318 ]],

       [[-0.60450986, -1.13186661],
        [ 0.11219452, -0.23632336],
        [-1.39770159, -0.99976877]]])

In [44]:
re.reshape(3,2,2)

array([[[ 0.66890184,  0.29318779],
        [ 0.44929895,  0.06175574]],

       [[ 1.17133333, -0.2299318 ],
        [-0.60450986, -1.13186661]],

       [[ 0.11219452, -0.23632336],
        [-1.39770159, -0.99976877]]])

In [45]:
re.reshape(2,1,6)

array([[[ 0.66890184,  0.29318779,  0.44929895,  0.06175574,
          1.17133333, -0.2299318 ]],

       [[-0.60450986, -1.13186661,  0.11219452, -0.23632336,
         -1.39770159, -0.99976877]]])

In [46]:
re

array([[[ 0.66890184,  0.29318779],
        [ 0.44929895,  0.06175574],
        [ 1.17133333, -0.2299318 ]],

       [[-0.60450986, -1.13186661],
        [ 0.11219452, -0.23632336],
        [-1.39770159, -0.99976877]]])

In [47]:
re.reshape(2,-1)

array([[ 0.66890184,  0.29318779,  0.44929895,  0.06175574,  1.17133333,
        -0.2299318 ],
       [-0.60450986, -1.13186661,  0.11219452, -0.23632336, -1.39770159,
        -0.99976877]])

In [53]:
re.reshape(4,3,-1)

array([[[ 0.66890184],
        [ 0.29318779],
        [ 0.44929895]],

       [[ 0.06175574],
        [ 1.17133333],
        [-0.2299318 ]],

       [[-0.60450986],
        [-1.13186661],
        [ 0.11219452]],

       [[-0.23632336],
        [-1.39770159],
        [-0.99976877]]])

In [52]:
re.reshape(6,-1)

array([[ 0.66890184,  0.29318779],
       [ 0.44929895,  0.06175574],
       [ 1.17133333, -0.2299318 ],
       [-0.60450986, -1.13186661],
       [ 0.11219452, -0.23632336],
       [-1.39770159, -0.99976877]])

In [55]:
re[::-1]

array([[[-0.60450986, -1.13186661],
        [ 0.11219452, -0.23632336],
        [-1.39770159, -0.99976877]],

       [[ 0.66890184,  0.29318779],
        [ 0.44929895,  0.06175574],
        [ 1.17133333, -0.2299318 ]]])

In [61]:
re[0:][1:]

array([[[-0.60450986, -1.13186661],
        [ 0.11219452, -0.23632336],
        [-1.39770159, -0.99976877]]])

In [64]:
re[:,1:]

array([[[ 0.44929895,  0.06175574],
        [ 1.17133333, -0.2299318 ]],

       [[ 0.11219452, -0.23632336],
        [-1.39770159, -0.99976877]]])

In [65]:
a2=np.random.randint(2,40,(4,5))

In [66]:
a2

array([[18, 37, 30, 10,  3],
       [38, 34, 31,  9, 30],
       [29, 13, 13, 14, 29],
       [25,  7, 10,  4,  5]])

In [72]:
a2[a2>20]

array([37, 30, 38, 34, 31, 30, 29, 29, 25])

In [74]:
a2[0,1]=78

In [75]:
a2

array([[18, 78, 30, 10,  3],
       [38, 34, 31,  9, 30],
       [29, 13, 13, 14, 29],
       [25,  7, 10,  4,  5]])

In [77]:
a4=np.random.randint(2,99,(3,3))

In [78]:
a3

array([[42, 23, 74],
       [40, 59, 86],
       [ 2, 95, 37]])

In [79]:
a4

array([[98, 81, 51],
       [10, 20,  5],
       [15, 53,  6]])

In [80]:
a3*a4

array([[4116, 1863, 3774],
       [ 400, 1180,  430],
       [  30, 5035,  222]])

In [82]:
a3@a4

array([[5456, 7784, 2701],
       [5800, 8978, 2851],
       [1701, 4023,  799]])

In [86]:
np.matmul(a3,a4)

array([[5456, 7784, 2701],
       [5800, 8978, 2851],
       [1701, 4023,  799]])

In [87]:
np.add(a3,100)

array([[142, 123, 174],
       [140, 159, 186],
       [102, 195, 137]])

In [88]:
np.add(a3,a4)

array([[140, 104, 125],
       [ 50,  79,  91],
       [ 17, 148,  43]])

In [90]:
np.divide(a3,0)

C:\Users\Sudha\AppData\Local\Temp\ipykernel_10272\3837936085.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(a3,0)


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [92]:
np.subtract(a3,a4)

array([[-56, -58,  23],
       [ 30,  39,  81],
       [-13,  42,  31]])

In [96]:
a3**2

array([[1764,  529, 5476],
       [1600, 3481, 7396],
       [   4, 9025, 1369]], dtype=int32)

In [99]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
np.diagonal(a3)

array([42, 59, 37])

In [107]:
a2

array([[18, 78, 30, 10,  3],
       [38, 34, 31,  9, 30],
       [29, 13, 13, 14, 29],
       [25,  7, 10,  4,  5]])

In [108]:
a2 + np.array([1,2,3,4,5])

array([[19, 80, 33, 14,  8],
       [39, 36, 34, 13, 35],
       [30, 15, 16, 18, 34],
       [26,  9, 13,  8, 10]])

In [113]:
(a2.T + np.array([1,2,3,4])).T

array([[19, 79, 31, 11,  4],
       [40, 36, 33, 11, 32],
       [32, 16, 16, 17, 32],
       [29, 11, 14,  8,  9]])

In [114]:
a2 + np.array([[1,2,3,4]]).T

array([[19, 79, 31, 11,  4],
       [40, 36, 33, 11, 32],
       [32, 16, 16, 17, 32],
       [29, 11, 14,  8,  9]])

In [116]:
np.sqrt(a3)

array([[6.4807407 , 4.79583152, 8.60232527],
       [6.32455532, 7.68114575, 9.2736185 ],
       [1.41421356, 9.74679434, 6.08276253]])

In [117]:
np.exp(a3)

array([[1.73927494e+18, 9.74480345e+09, 1.37338298e+32],
       [2.35385267e+17, 4.20121040e+25, 2.23524660e+37],
       [7.38905610e+00, 1.81123908e+41, 1.17191424e+16]])

In [118]:
np.log10(a3)

array([[1.62324929, 1.36172784, 1.86923172],
       [1.60205999, 1.77085201, 1.93449845],
       [0.30103   , 1.97772361, 1.56820172]])

In [119]:
np.log2(a3)

array([[5.39231742, 4.52356196, 6.20945337],
       [5.32192809, 5.88264305, 6.42626475],
       [1.        , 6.56985561, 5.20945337]])

In [120]:
np.log(a3)

array([[3.73766962, 3.13549422, 4.30406509],
       [3.68887945, 4.07753744, 4.4543473 ],
       [0.69314718, 4.55387689, 3.61091791]])

In [127]:
np.arange(10,30,2.5)

array([10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5])

In [134]:
np.linspace(1,5,num=50,retstep=True)

(array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
        1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
        1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
        2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
        2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
        3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
        3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
        3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
        4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
        4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ]),
 0.08163265306122448)

In [136]:
np.logspace(1,5,num=4,base=10)

array([1.00000000e+01, 2.15443469e+02, 4.64158883e+03, 1.00000000e+05])

In [137]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])